### ISSUE TITLE
[DOC] add readme to published package

### ISSUE THREAD

**Issue by toddbaert** [open-feature/dotnet-sdk#138]
### Change in the documentation

We currently don't have a readme being published.

We can do follow these steps to do that: https://devblogs.microsoft.com/nuget/add-a-readme-to-your-nuget-package/#add-a-readme-to-your-package

**Comment by askpt** [comment]
@toddbaert and @beeme1mr it seems my PR didn't fix the issue. Could you please reopen this task?

**Comment by askpt** [comment]
I was reading this article and it seems we have some badges that are not in the Nuget whitelist: https://learn.microsoft.com/en-us/NuGet/nuget-org/package-readme-on-nuget-org#allowed-domains-for-images-and-badges

Since I am not the package owner, it is hard to understand what is going on under the hood. Could someone help me with this bit here?
@beeme1mr @toddbaert

**Comment by beeme1mr** [comment]
Hey @askpt, here's what I discovered. First, the readme isn't live on NuGet yet because we haven't released an update. We were waiting for support for events before releasing an update. That feature was just added, so a release should happen soon.

I also spent some time looking into the markdown restrictions that NuGet has. Unfortunately, they don't support some of the HTML elements we use and they're rendered as plain text. [Here's a GitHub issue](https://github.com/NuGet/NuGetGallery/issues/8644) that shows all the missing features. It also looks like `https://bestpractices.coreinfrastructure.org/projects/6250/badge` will be blocked but the NuGet team has a process to get a new domain added to their allow list.

I think the biggest issue is the lack of HTML support in NuGet. We may want to write a script that strips HTML. We already have `x-hide-in-docs-start` and e `x-hide-in-docs-end` tags that could be used to remove unwanted content.

What do you think @askpt? FYI @toddbaert

**Comment by askpt** [comment]
Sorry @beeme1mr got confused between the contrib and SDK packages. I thought there was a new version for the SDK with the PR that introduces the NuGet feature.
In relation to your point, might be useful looking into a new tag just to show/hide when published to the NuGet.
For the badges, you're right. Might be worth trying to have the other team to add the domains to the whitelist.

**Comment by beeme1mr** [comment]
I'll submit a request to add the domain.

**Comment by askpt** [comment]
As suspected, the HTML is not rendered correctly. We need to revisit this issue to fix them: https://www.nuget.org/packages/OpenFeature

**Comment by toddbaert** [comment]
> As suspected, the HTML is not rendered correctly. We need to revisit this issue to fix them: https://www.nuget.org/packages/OpenFeature

:weary:
